"""rekomendacjeupdate

Revision ID: 2227ac13e9bb
Revises: 50195f8b3271
Create Date: 2025-09-01 15:30:21.465496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2227ac13e9bb'
down_revision: Union[str, None] = '50195f8b3271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_movie_recommendation', 'recommendations', ['user_id', 'movie_id'])
    op.drop_column('recommendations', 'algorithm_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('algorithm_used', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('unique_user_movie_recommendation', 'recommendations', type_='unique')
    # ### end Alembic commands ###
