"""time at watchlist3

Revision ID: 2e9654fb5096
Revises: 79ddf8b69d1c
Create Date: 2025-04-24 09:12:32.192268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9654fb5096'
down_revision: Union[str, None] = '79ddf8b69d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_movie_watchlist', 'watchlist', type_='unique')
    op.drop_column('watchlist', 'watchlist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('watchlist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('unique_user_movie_watchlist', 'watchlist', ['user_id', 'movie_id'])
    # ### end Alembic commands ###
