"""add time to favcorite movie

Revision ID: 3576552658a0
Revises: 3e7b311aa7de
Create Date: 2025-04-23 19:43:58.277704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3576552658a0'
down_revision: Union[str, None] = '3e7b311aa7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_movies', sa.Column('added_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_movies', 'added_at')
    # ### end Alembic commands ###
