"""authlogin

Revision ID: 50195f8b3271
Revises: d64a55f88bcd
Create Date: 2025-05-26 15:17:35.187861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50195f8b3271"
down_revision: Union[str, None] = "d64a55f88bcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(length=100), nullable=True))
    op.add_column(
        "users", sa.Column("facebook_id", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("github_id", sa.String(length=100), nullable=True))
    op.add_column(
        "users", sa.Column("oauth_provider", sa.String(length=20), nullable=True)
    )

    # Dodaj oauth_created jako nullable najpierw
    op.add_column("users", sa.Column("oauth_created", sa.Boolean(), nullable=True))

    # Ustaw domyślną wartość False dla wszystkich istniejących użytkowników
    op.execute("UPDATE users SET oauth_created = false WHERE oauth_created IS NULL")

    # Teraz zmień kolumnę na NOT NULL
    op.alter_column("users", "oauth_created", nullable=False)

    # Zmień password_hash na nullable
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True
    )

    # Dodaj indeksy
    op.create_index(op.f("ix_users_facebook_id"), "users", ["facebook_id"], unique=True)
    op.create_index(op.f("ix_users_github_id"), "users", ["github_id"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_github_id"), table_name="users")
    op.drop_index(op.f("ix_users_facebook_id"), table_name="users")
    op.alter_column(
        "users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("users", "oauth_created")
    op.drop_column("users", "oauth_provider")
    op.drop_column("users", "github_id")
    op.drop_column("users", "facebook_id")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
