"""time at watchlist

Revision ID: 79ddf8b69d1c
Revises: 3576552658a0
Create Date: 2025-04-24 09:10:37.909691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ddf8b69d1c'
down_revision: Union[str, None] = '3576552658a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('watchlist_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('watchlist', sa.Column('added_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint('unique_user_movie_watchlist', 'watchlist', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_movie_watchlist', 'watchlist', type_='unique')
    op.drop_column('watchlist', 'added_at')
    op.drop_column('watchlist', 'watchlist_id')
    # ### end Alembic commands ###
