"""time at watchlist5

Revision ID: b26a7d968508
Revises: 6905fe1c4986
Create Date: 2025-04-24 09:16:33.810356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b26a7d968508'
down_revision: Union[str, None] = '6905fe1c4986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('rated_at', sa.DateTime(), nullable=False))
    op.drop_column('watchlist', 'added_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('watchlist', 'rated_at')
    # ### end Alembic commands ###
