"""notification

Revision ID: b436c8e6106e
Revises: 7fbc7452bb16
Create Date: 2025-09-05 14:23:31.670007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b436c8e6106e"
down_revision: Union[str, None] = "7fbc7452bb16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # USUŃ TĘ LINIJKĘ - powoduje błąd i nie jest potrzebna:
    # op.alter_column('actors', 'biography',
    #            existing_type=sa.TEXT(),
    #            type_=sa.String(length=2000),
    #            existing_nullable=False)

    # Dodaj pole notification z domyślną wartością 1
    op.add_column(
        "users",
        sa.Column("notification", sa.Integer(), nullable=False, server_default="1"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Usuń pole notification
    op.drop_column("users", "notification")

    # USUŃ TĘ LINIJKĘ - odpowiada usunięcej zmianie w upgrade():
    # op.alter_column('actors', 'biography',
    #            existing_type=sa.String(length=2000),
    #            type_=sa.TEXT(),
    #            existing_nullable=False)

    # ### end Alembic commands ###
