"""director_change

Revision ID: d64a55f88bcd
Revises: 0e28661b4850
Create Date: 2025-05-05 14:55:56.401004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64a55f88bcd'
down_revision: Union[str, None] = '0e28661b4850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directors', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.add_column('directors', sa.Column('gender', sa.Enum('M', 'K', name='gender'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directors', 'gender')
    op.drop_column('directors', 'photo_url')
    # ### end Alembic commands ###
