"""time at watchlist8

Revision ID: df103fcfa351
Revises: 4d5a93cea588
Create Date: 2025-04-24 09:44:25.450691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df103fcfa351'
down_revision: Union[str, None] = '4d5a93cea588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('added_at', sa.DateTime(), nullable=False))
    op.drop_column('watchlist', 'rated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist', sa.Column('rated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('watchlist', 'added_at')
    # ### end Alembic commands ###
