"""Add actross_url

Revision ID: f4b1d2be9a27
Revises: 2acd335a7e8f
Create Date: 2025-04-01 19:50:47.240678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b1d2be9a27'
down_revision: Union[str, None] = '2acd335a7e8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'photo_url')
    # ### end Alembic commands ###
