"""Initial migration

Revision ID: bb6728b93284
Revises: 
Create Date: 2026-02-12 11:14:46.420140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6728b93284'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_replies',
    sa.Column('reply_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_main', sa.Integer(), nullable=False),
    sa.Column('comment_main_id', sa.Integer(), nullable=False),
    sa.Column('id_reply', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_main_id'], ['comments.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_main'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_reply'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reply_id')
    )
    with op.batch_alter_table('comment_replies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_replies_comment_main_id'), ['comment_main_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_replies_id_main'), ['id_main'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_replies_id_reply'), ['id_reply'], unique=False)

    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_id'], ['comment_replies.reply_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_reply_id'), ['reply_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_reply_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_comment_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('comment_replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_replies_id_reply'))
        batch_op.drop_index(batch_op.f('ix_comment_replies_id_main'))
        batch_op.drop_index(batch_op.f('ix_comment_replies_comment_main_id'))

    op.drop_table('comment_replies')
    # ### end Alembic commands ###
